// packages/angular/src/use-fae-entity.ts
import { effect, signal, type Signal } from '@angular/core';
import type { AsyncState, EntityService } from '@fae/core';
import { idleState, loadingState } from './async-state.js';

export type FaeEntityIdSource = string | null | undefined | Signal<string | null | undefined>;

function resolveId(id: FaeEntityIdSource): string | null | undefined {
  return typeof id === 'function' ? id() : id;
}

/**
 * Generic Angular bridge — subscribes to any {@link EntityService} and exposes a Signal.
 *
 * Must be called in an injection context (constructor, field initializer, `runInInjectionContext`).
 *
 * @param id - Entity id or a Signal of id; `null` / `undefined` resets to `idle`.
 */
export function useFaeEntity<T>(
  service: EntityService<T>,
  id: FaeEntityIdSource,
): Signal<AsyncState<T>> {
  const state = signal<AsyncState<T>>(
    resolveId(id) ? loadingState<T>() : idleState<T>(),
  );

  effect((onCleanup) => {
    const currentId = resolveId(id);

    if (!currentId) {
      state.set(idleState<T>());
      return;
    }

    state.set(loadingState<T>());
    const unsubscribe = service.subscribe(currentId, (next) => {
      state.set(next);
    });
    onCleanup(() => unsubscribe());
  });

  return state.asReadonly();
}

// packages/react/src/useFaeEntity.ts
import { useEffect, useState } from 'react';
import type { AsyncState, EntityService } from '@fae/core';

function idleState<T>(): AsyncState<T> {
  return { status: 'idle', data: null, error: null };
}

function loadingState<T>(): AsyncState<T> {
  return { status: 'loading', data: null, error: null };
}

/**
 * Generic React bridge — subscribes to any {@link EntityService} and maps to React state.
 *
 * @param id - Entity id; pass `null` or `undefined` to reset to `idle`.
 */
export function useFaeEntity<T>(
  service: EntityService<T>,
  id: string | null | undefined,
): AsyncState<T> {
  const [state, setState] = useState<AsyncState<T>>(() =>
    id ? loadingState<T>() : idleState<T>(),
  );

  useEffect(() => {
    if (!id) {
      setState(idleState<T>());
      return;
    }

    setState(loadingState<T>());
    return service.subscribe(id, setState);
  }, [id, service]);

  return state;
}
